### ISSUE TITLE
Time error in countdown

### ISSUE THREAD

**Issue by menagerie198** [rafaelveiga/obsidian-widgets#10]
There seems to be a disconnect between the time in the clock and the countdown widget. There is a three hour 30 minutes difference in them (see image). the countdown is set for 20:30. 
I tried closing down and reinstalling but the issue remained.
![image](https://github.com/rafaelveiga/obsidian-widgets/assets/7330436/75196c86-00db-4d06-baaf-aa924347916c)

UPDATE: I've done a bit of basic maths! It seems to be counting down to midnight/the next day, rather than the time I set (2024-01-28 20:30:00)

**Comment by bradmccormick** [comment]
Agreed --- it's counting down to midnight instead of the time I have specified.  Since it's so granular (down to the second), it would be great if it would honor the time of day specified.

**Comment by rafaelveiga** [comment]
Thanks for reporting! IIRC we do countdown until midnight and don't consider the time provided in the configuration. I'm going to fix this. Added to our roadmap/issue tracker

**Comment by rafaelveiga** [comment]
This is fixed and should be on the next release
