### ISSUE TITLE
Feature request: Widget to play a local music file

### ISSUE THREAD

**Issue by Gourav1910** [rafaelveiga/obsidian-widgets#16]
I want a widget which is similar to quote widget but here in place of quote I should select a local music file which should also be playable in widget. Or I should pause as well and a slider of music to move forward and backward. 

I want this feature because I write stories and I always write it with the inspirations of music and songs. So I want to add my music file in between text of stories as widgets so that I can instantly play it also which will increase my experience of writing or developing stories. I don't know whether I explained it well or not but if it is possible please add this widget.

I want that whenever I open that note then my widget should always be there and I can play the music. We can also directly add the music file also in the note but widget will add lot of aesthetic to it. And also we can add some information text just like we add author to the quote widget.

**Comment by kraibse** [comment]
Could this be what you're looking for?

https://github.com/noonesimg/obsidian-audio-player
obsidian://show-plugin?id=obsidian-audio-player

**Comment by rafaelveiga** [comment]
Thanks for the suggestion @Gourav1910! Since the `obsidian-audio-player` does the same as you suggested, I'm going to punt this for a future release of Obsidian Widgets
