### ISSUE TITLE
Countdown not showing proper countdown 

### ISSUE THREAD

**Issue by lilchichi** [rafaelveiga/obsidian-widgets#18]
Same issue as [Docfips](https://github.com/Docfips) had with his [closed issue](https://github.com/rafaelveiga/obsidian-widgets/issues/17) of the timer not working properly, however I'm not a dev & not sure how to fix this? @rafaelveiga

**Comment by smarj** [comment]
#19 is a dupe, but I've left a fix there.

**Comment by rafaelveiga** [comment]
I've just pushed release 0.0.7 with @PrabalSaxena01 fixes, which should fix the countdown issues.

I'm closing this issue and keeping the discussion active on #19
