### ISSUE TITLE
Countdown does not work when I add dates that are more than 28 days away?

### ISSUE THREAD

**Issue by PrabalSaxena01** [rafaelveiga/obsidian-widgets#19]
I tried to Add countdown to dates 21st April. 2024. but it showed 28 days away. Same happen when I started a countdown for 21st June.

**Comment by smarj** [comment]
Looks like a fix is coming, but no release yet. What worked for me was taking the new fix and modifying my `main.js` file in the countdown widget's plugin code.

There's a section of code with `duration.days()`. I changed that to `Math.floor(duration / 86400000)`. It's working out to at least 153 days now. I got the bit to change from a closed issue (#17), but that fix now breaks the whole thing. This code modified from the latest PR seems to be working, though.

**Comment by rafaelveiga** [comment]
I've just pushed release 0.0.7 with @PrabalSaxena01 fixes, which should fix the countdown issues

**Comment by rafaelveiga** [comment]
I'll left the discussion open here if any bugs appear in this 0.0.7 release for the countdown widget

**Comment by rafaelveiga** [comment]
Seems that no issues appeared on the 0.0.7 release. Closing this issue for now. If you enconter a bug with this widget, please open a new issue!
