### ISSUE TITLE
FR: Ability to change the colour/style of the widget?

### ISSUE THREAD

**Issue by ernest67** [rafaelveiga/obsidian-widgets#3]
I really like this plug-in and thank you for your time and effort in developing this. Was wondering whether you could add a way so that we can customise the colour or style of the widget? Again, really appreciate the work!

**Comment by rafaelveiga** [comment]
Thanks for the feedback and thanks for using the plugin! Currently the widget respects the theme's color properties. 

To keep the widget API simple, I would prefer not to add color styles to the code block markdown and keep it configuration only

My suggestion would be using **CSS Snippets** to customize the look of your widgets. I'm not sure how familiar you are with CSS but I can point you to the right direction, if needed. 

The classes for each widget are located in their respective folders in /src/:
[CSS Classes for Clock](https://github.com/rafaelveiga/obsidian-widgets/blob/master/src/Clock/index.tsx)
[CSS Classes for Countdown](https://github.com/rafaelveiga/obsidian-widgets/blob/master/src/Countdown/index.tsx)
[CSS Classes for Quote](https://github.com/rafaelveiga/obsidian-widgets/blob/master/src/Quote/index.tsx)

**Comment by rafaelveiga** [comment]
I've added a [wiki page](https://github.com/rafaelveiga/obsidian-widgets/wiki/Customizing-your-widgets-colors-styles) that guides you on how to write your CSS Snippets
