### ISSUE TITLE
Feature request: Multiple counters per note

### ISSUE THREAD

**Issue by ZeroKun265** [rafaelveiga/obsidian-widgets#39]
I'd love to be able to store multiple counters per note, maybe keeping the default behaviour by having one general counter per note, but then having other counters be able to e a sort of id like 
````
```widgets
type: counter
text: General
```
````

Will give the note counter but then 
````
```widgets
type: counter
text: Specific
id: "Test"
```
````

would be a separate counter (The id could be numeric or with strings, that's not important lol)

**Comment by rafaelveiga** [comment]
Loved the id suggestion. Currently we do support only one widget per note, but I think that with the ID we could work with multiple. Will add that to the idea list

**Comment by rafaelveiga** [comment]
This has been adressed on #42. Should be included in the next release
